# Generated by Django 3.1.3 on 2020-11-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('professional_experience', models.CharField(max_length=50)),
                ('skills', models.CharField(max_length=50)),
                ('organizations', models.CharField(max_length=50)),
                ('coding_projects', models.CharField(max_length=50)),
            ],
        ),
    ]
